### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by arjunkalburgi** [afontaine/ECE421#1]
# TODO 

- [ ] - Questions (gdrive document)
- [ ] - Make sure gemfiles are proper https://stackoverflow.com/questions/30358612/how-to-create-a-gemfile
- [ ] - Fill assignment1_main.rb with features??? I think. heh. 
- [ ] - Build out factory in /sparsematrixpackage, use: https://medium.com/@dljerome/design-patterns-in-ruby-factory-method-e4e4cd995254
- [ ] - Build sparsematrix class with https://docs.ruby-lang.org/en/2.0.0/Hash.html
- [ ] - Make sure everything we write is complient with https://ruby-doc.org/stdlib-- 1.8.7/libdoc/test/unit/rdoc/Test/Unit.html
- [ ] - 
- [ ] -
